### ISSUE TITLE
error while making account

### ISSUE THREAD

**Issue by catn1pdeal3r** [Bluyx/Kick.com-account-generator#9]
I don't know the issue

Traceback (most recent call last):
  File "C:\Users\aleve\Downloads\Kick.com-account-generator-main\Kick.com-account-generator-main\main.py", line 129, in <module>
    generate(f"{username}{acc}")
  File "C:\Users\aleve\Downloads\Kick.com-account-generator-main\Kick.com-account-generator-main\main.py", line 73, in generate
    asyncio.run(kick.kick(useKopeechka=useKopeechka, password=pw, username=username, kopeechkaToken=config["kopeechka"]["kopeechkaToken"], domain=config["kopeechka"]["domain"], apiURL=config["apiURL"], customDomain=config["domain"], imap=config["imap"], optionalRequests=False, debug=True, proxy=proxy, saveAs=saveAs).create_account())
  File "C:\Users\aleve\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\aleve\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\aleve\Downloads\Kick.com-account-generator-main\Kick.com-account-generator-main\kick.py", line 146, in create_account
    code = getVerification(email=self.email, password=self.password, sender="ALL", verification_location="subject", imap=self.imap)
TypeError: getVerification() missing 1 required positional argument: 'apiURL

**Comment by Bluyx** [comment]
831832c8c4a233a866e9ea7efd11bf727ca395cf

**Comment by Bluyx** [comment]
Fixed; it was missing an argument
831832c8c4a233a866e9ea7efd11bf727ca395cf

**Comment by Bluyx** [comment]
Fixed; it was missing an argument
831832c8c4a233a866e9ea7efd11bf727ca395cf

**Comment by Bluyx** [comment]
Fixed; it was missing an argument
831832c8c4a233a866e9ea7efd11bf727ca395cf
